//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMMYA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Excel_ReadEntities : DbContext
    {
        public Excel_ReadEntities()
            : base("name=Excel_ReadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BankDetail> BankDetails { get; set; }
        public DbSet<Ph_Sec_Excel> Ph_Sec_Excel { get; set; }
    
        public virtual int usp_ReadDataInsert(Nullable<int> sr_No, string bankName, string bankBranch, string iFSCCode, string app_Reg, string loan_Category, string firstName, string middleName, string lastName, string gender, string maritalStatus, Nullable<System.DateTime> dob, string village, string gram, string tehsil, string block, string district, string religion, string minority_Comm, string social_Category, string aadhar, string pAN, string mobile, string email, Nullable<int> reqLoanAmnt, Nullable<int> sanctionAmnt, Nullable<System.DateTime> sanctionDate, string business_Activity, string type_Loan, Nullable<int> disbursedAmnt, Nullable<System.DateTime> disburseDate, Nullable<int> loanAmntOutStanding, string status)
        {
            var sr_NoParameter = sr_No.HasValue ?
                new ObjectParameter("Sr_No", sr_No) :
                new ObjectParameter("Sr_No", typeof(int));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("BankName", bankName) :
                new ObjectParameter("BankName", typeof(string));
    
            var bankBranchParameter = bankBranch != null ?
                new ObjectParameter("BankBranch", bankBranch) :
                new ObjectParameter("BankBranch", typeof(string));
    
            var iFSCCodeParameter = iFSCCode != null ?
                new ObjectParameter("IFSCCode", iFSCCode) :
                new ObjectParameter("IFSCCode", typeof(string));
    
            var app_RegParameter = app_Reg != null ?
                new ObjectParameter("App_Reg", app_Reg) :
                new ObjectParameter("App_Reg", typeof(string));
    
            var loan_CategoryParameter = loan_Category != null ?
                new ObjectParameter("Loan_Category", loan_Category) :
                new ObjectParameter("Loan_Category", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var maritalStatusParameter = maritalStatus != null ?
                new ObjectParameter("MaritalStatus", maritalStatus) :
                new ObjectParameter("MaritalStatus", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("Dob", dob) :
                new ObjectParameter("Dob", typeof(System.DateTime));
    
            var villageParameter = village != null ?
                new ObjectParameter("Village", village) :
                new ObjectParameter("Village", typeof(string));
    
            var gramParameter = gram != null ?
                new ObjectParameter("Gram", gram) :
                new ObjectParameter("Gram", typeof(string));
    
            var tehsilParameter = tehsil != null ?
                new ObjectParameter("Tehsil", tehsil) :
                new ObjectParameter("Tehsil", typeof(string));
    
            var blockParameter = block != null ?
                new ObjectParameter("Block", block) :
                new ObjectParameter("Block", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("District", district) :
                new ObjectParameter("District", typeof(string));
    
            var religionParameter = religion != null ?
                new ObjectParameter("Religion", religion) :
                new ObjectParameter("Religion", typeof(string));
    
            var minority_CommParameter = minority_Comm != null ?
                new ObjectParameter("Minority_Comm", minority_Comm) :
                new ObjectParameter("Minority_Comm", typeof(string));
    
            var social_CategoryParameter = social_Category != null ?
                new ObjectParameter("Social_Category", social_Category) :
                new ObjectParameter("Social_Category", typeof(string));
    
            var aadharParameter = aadhar != null ?
                new ObjectParameter("Aadhar", aadhar) :
                new ObjectParameter("Aadhar", typeof(string));
    
            var pANParameter = pAN != null ?
                new ObjectParameter("PAN", pAN) :
                new ObjectParameter("PAN", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var reqLoanAmntParameter = reqLoanAmnt.HasValue ?
                new ObjectParameter("ReqLoanAmnt", reqLoanAmnt) :
                new ObjectParameter("ReqLoanAmnt", typeof(int));
    
            var sanctionAmntParameter = sanctionAmnt.HasValue ?
                new ObjectParameter("SanctionAmnt", sanctionAmnt) :
                new ObjectParameter("SanctionAmnt", typeof(int));
    
            var sanctionDateParameter = sanctionDate.HasValue ?
                new ObjectParameter("SanctionDate", sanctionDate) :
                new ObjectParameter("SanctionDate", typeof(System.DateTime));
    
            var business_ActivityParameter = business_Activity != null ?
                new ObjectParameter("Business_Activity", business_Activity) :
                new ObjectParameter("Business_Activity", typeof(string));
    
            var type_LoanParameter = type_Loan != null ?
                new ObjectParameter("Type_Loan", type_Loan) :
                new ObjectParameter("Type_Loan", typeof(string));
    
            var disbursedAmntParameter = disbursedAmnt.HasValue ?
                new ObjectParameter("DisbursedAmnt", disbursedAmnt) :
                new ObjectParameter("DisbursedAmnt", typeof(int));
    
            var disburseDateParameter = disburseDate.HasValue ?
                new ObjectParameter("DisburseDate", disburseDate) :
                new ObjectParameter("DisburseDate", typeof(System.DateTime));
    
            var loanAmntOutStandingParameter = loanAmntOutStanding.HasValue ?
                new ObjectParameter("LoanAmntOutStanding", loanAmntOutStanding) :
                new ObjectParameter("LoanAmntOutStanding", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ReadDataInsert", sr_NoParameter, bankNameParameter, bankBranchParameter, iFSCCodeParameter, app_RegParameter, loan_CategoryParameter, firstNameParameter, middleNameParameter, lastNameParameter, genderParameter, maritalStatusParameter, dobParameter, villageParameter, gramParameter, tehsilParameter, blockParameter, districtParameter, religionParameter, minority_CommParameter, social_CategoryParameter, aadharParameter, pANParameter, mobileParameter, emailParameter, reqLoanAmntParameter, sanctionAmntParameter, sanctionDateParameter, business_ActivityParameter, type_LoanParameter, disbursedAmntParameter, disburseDateParameter, loanAmntOutStandingParameter, statusParameter);
        }
    }
}
