//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error!.
        /// </summary>
        internal static string App_Error_Head {
            get {
                return ResourceManager.GetString("App_Error_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report To Us.
        /// </summary>
        internal static string App_Error_ReportUs {
            get {
                return ResourceManager.GetString("App_Error_ReportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered a temporary error and could not complete your request. &lt;br/&gt; Please try back in few minutes. &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; If you still receive this error, please report to the system administrator..
        /// </summary>
        internal static string App_Error_Text {
            get {
                return ResourceManager.GetString("App_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btnABlack {
            get {
                return ResourceManager.GetString("btnABlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string btnABlackToolTip {
            get {
                return ResourceManager.GetString("btnABlackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btnAWhite {
            get {
                return ResourceManager.GetString("btnAWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Contrast.
        /// </summary>
        internal static string btnAWhiteToolTip {
            get {
                return ResourceManager.GetString("btnAWhiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string btnContactUs {
            get {
                return ResourceManager.GetString("btnContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string btn_Language {
            get {
                return ResourceManager.GetString("btn_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        internal static string btn_Large {
            get {
                return ResourceManager.GetString("btn_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A++.
        /// </summary>
        internal static string btn_Larger {
            get {
                return ResourceManager.GetString("btn_Larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Largest Font.
        /// </summary>
        internal static string btn_LargerToolTip {
            get {
                return ResourceManager.GetString("btn_LargerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Larger Font.
        /// </summary>
        internal static string btn_LargeToolTip {
            get {
                return ResourceManager.GetString("btn_LargeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btn_Medium {
            get {
                return ResourceManager.GetString("btn_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Medium Font.
        /// </summary>
        internal static string btn_MediumToolTip {
            get {
                return ResourceManager.GetString("btn_MediumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        internal static string btn_Small {
            get {
                return ResourceManager.GetString("btn_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A--.
        /// </summary>
        internal static string btn_Smallest {
            get {
                return ResourceManager.GetString("btn_Smallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Smallest Font.
        /// </summary>
        internal static string btn_SmallestToolTip {
            get {
                return ResourceManager.GetString("btn_SmallestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Smaller Font.
        /// </summary>
        internal static string btn_SmallToolTip {
            get {
                return ResourceManager.GetString("btn_SmallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurangabad , IN.
        /// </summary>
        internal static string CityAurangabad {
            get {
                return ResourceManager.GetString("CityAurangabad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mecca, SA.
        /// </summary>
        internal static string CityMecca {
            get {
                return ResourceManager.GetString("CityMecca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medina, SA.
        /// </summary>
        internal static string CityMedina {
            get {
                return ResourceManager.GetString("CityMedina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumbai, IN.
        /// </summary>
        internal static string CityMumbai {
            get {
                return ResourceManager.GetString("CityMumbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagpur, IN.
        /// </summary>
        internal static string CityNagpur {
            get {
                return ResourceManager.GetString("CityNagpur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Person.
        /// </summary>
        internal static string heading {
            get {
                return ResourceManager.GetString("heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string HeadLoginStatus {
            get {
                return ResourceManager.GetString("HeadLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001/Home&apos;&gt;Home.
        /// </summary>
        internal static string HomepagePath {
            get {
                return ResourceManager.GetString("HomepagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string HyperLink1 {
            get {
                return ResourceManager.GetString("HyperLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Information Technology Corporation Limited..
        /// </summary>
        internal static string imgMahaIT_alt {
            get {
                return ResourceManager.GetString("imgMahaIT_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string lblAlbum {
            get {
                return ResourceManager.GetString("lblAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra State Pradhan Mantri Mudra Yojana , Government of Maharashtra.
        /// </summary>
        internal static string lbldepName {
            get {
                return ResourceManager.GetString("lbldepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string lblGallery {
            get {
                return ResourceManager.GetString("lblGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Search.
        /// </summary>
        internal static string lblKeywordsearch {
            get {
                return ResourceManager.GetString("lblKeywordsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivational.
        /// </summary>
        internal static string lblMotivational {
            get {
                return ResourceManager.GetString("lblMotivational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        internal static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More News Update.
        /// </summary>
        internal static string lblNewsMore {
            get {
                return ResourceManager.GetString("lblNewsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for new user registration.
        /// </summary>
        internal static string lblNewUserRegister {
            get {
                return ResourceManager.GetString("lblNewUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string lblPhoto {
            get {
                return ResourceManager.GetString("lblPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Reviewed:.
        /// </summary>
        internal static string lblReviewDate {
            get {
                return ResourceManager.GetString("lblReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearchBTN {
            get {
                return ResourceManager.GetString("lblSearchBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are searching for this word :.
        /// </summary>
        internal static string lblSearchword {
            get {
                return ResourceManager.GetString("lblSearchword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string lblsitemap {
            get {
                return ResourceManager.GetString("lblsitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Start Date :.
        /// </summary>
        internal static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Stories.
        /// </summary>
        internal static string lblSuccessStories {
            get {
                return ResourceManager.GetString("lblSuccessStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Count:.
        /// </summary>
        internal static string lblTodaysVisitor {
            get {
                return ResourceManager.GetString("lblTodaysVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors :.
        /// </summary>
        internal static string lblTotalVisitor {
            get {
                return ResourceManager.GetString("lblTotalVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Site.
        /// </summary>
        internal static string lblViewPartnersHeading {
            get {
                return ResourceManager.GetString("lblViewPartnersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © This is the official website of Planning Department, Government of Maharashtra. All Rights Reserved..
        /// </summary>
        internal static string lbl_copyright {
            get {
                return ResourceManager.GetString("lbl_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pradhan Mantri Mudra Yojana &lt;br/&gt;&lt;span&gt;Government of Maharashtra&lt;/span&gt;.
        /// </summary>
        internal static string lbl_headTitle {
            get {
                return ResourceManager.GetString("lbl_headTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Content.
        /// </summary>
        internal static string lbl_skipToContent {
            get {
                return ResourceManager.GetString("lbl_skipToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Navigation.
        /// </summary>
        internal static string lbl_skipToNav {
            get {
                return ResourceManager.GetString("lbl_skipToNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of India.
        /// </summary>
        internal static string NationalEmblem_alt {
            get {
                return ResourceManager.GetString("NationalEmblem_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        internal static string searchTxtBox {
            get {
                return ResourceManager.GetString("searchTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_btn {
            get {
                return ResourceManager.GetString("Search_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here :.
        /// </summary>
        internal static string SitemapMsg {
            get {
                return ResourceManager.GetString("SitemapMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for visiting Pradhan Mantri Mudra Yojana Maharashtra State Website..
        /// </summary>
        internal static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
